### ISSUE TITLE
Packaged WAR application with this plugin have initializing error

### ISSUE THREAD

**Issue by fbxie** [bertramdev/imports#1]
bulk-data-imports plug-in version 0.1.1
My application works while using grails run-app command, but not when I uploaded the war package to server, there's a problem.
The error stack :
2014-05-07 18:38:03,843 [pool-2-thread-4] ERROR context.ContextLoader  - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplication' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.ExceptionInInitializerError
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ExceptionInInitializerError
    at java.lang.Class.forName(Class.java:270)
    ... 5 more
Caused by: java.lang.NullPointerException: Cannot get property 'metadata' on null object
    at grails.plugins.imports.ImportsService.<clinit>(ImportsService.groovy:9)
    ... 6 more

I'm afraid should not reference grailsApplication for static block at line 9 of ImportsService.groovy:
static rabbitQueue = "${grails.util.Holders.grailsApplication.metadata['app.name']}ImportRows"

**Comment by tmcgrath** [comment]
I'm running this too.  Any fixes?

**Comment by thejoyofabc** [comment]
I'm having the same problem.

**Comment by fbxie** [comment]
A workaround: If you guys don't use rabbit MQ in your application, you can simply comment the rabbitQueue lines out in the ImportService.groovy source file.

**Comment by fbxie** [comment]
It seems the author fixed this 2 months ago. Great!
